server:
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  management:
    endpoint:
      gateway:
        enabled: true
    endpoints: 
      web:
        exposure:
          include: gateway
